### ISSUE TITLE
remove werror option in release mode

### ISSUE THREAD

**Issue by finostro-amtc** [Livox-SDK/livox_ros_driver#10]
Hello, 

I am building your library with the latest version of pcl , where I get
```
/opt/ros/melodic/include/pcl_ros/point_cloud.h:51:18:` error: ‘using uint32_t = uint32_t’ is deprecated: use std::uint32_t instead of pcl::uint32_t [-Werror=deprecated-declarations]`
```
warnings. So I had to remove the  `-werror`  compiler flag  for the compilation to work. 
I understand why you develop with werror, but since users won't be fixing this stuff could you turn it off in release mode? 

Thank you

**Comment by Livox-SDK** [comment]
ok!
