### ISSUE TITLE
Convert rosbag with Livox CustomMsg to rosbag with PointCloud2 

### ISSUE THREAD

**Issue by digiamm** [Livox-SDK/livox_ros_driver#104]
Hi, is there any way straightforward way I can convert a rosbag with Livox `CustomMsg` point cloud to a rosbag with ROS `PointCloud2` format? 

Thank you in advance

**Comment by zaalsabb** [comment]
@digiamm Hi, were you able to figure out how to convert bags with `CustomMsg` messages to `PointCloud2` messages? I would really appreciate it.

Thanks!
Zaid

**Comment by maxpolzin** [comment]
I'd appreciate your inputs on this subject as well.

**Comment by maxpolzin** [comment]
@digiamm  Did figure out how to convert between CustomMsg and PointCloud2 message?
I'd appreciate your inputs.

**Comment by nilesh-hampi** [comment]
Did anyone figure it out?

**Comment by juliangaal** [comment]
I ran across the same problem, and couldn't find the functionality in the driver, as it expects the raw lidar packets from the sensor.

Therefore, I wrote a conversion node, available [here](https://github.com/juliangaal/livox2pointcloud). From there, just re-record the topics to create the bagfile.
