### ISSUE TITLE
Build failing in 16.04/Kinetic due to PCL bug

### ISSUE THREAD

**Issue by zlacelle** [Livox-SDK/livox_ros_driver#13]
Build fails with the following errors:

<command-line>:0:15: error: ISO C++11 requires whitespace after the macro name [-Werror]
<command-line>:0:15: error: ISO C++11 requires whitespace after the macro name [-Werror]
<command-line>:0:15: error: ISO C++11 requires whitespace after the macro name [-Werror]

These are caused because of some bug with PCL and the cmake definitions that include the following:

-DDISABLE_LIBUSB-1.0

The dash after LIBUSB is an invalid character. See: https://github.com/PointCloudLibrary/pcl/issues/1406

This issue was closed, but I'm guessing that PCL in 16.04 doesn't have the fix. I've verified this with a clean environment and brand new installs of everything.

Suggested fix: instead of using PCL directly in package.xml/CMakeLists.txt, use pcl_ros. This works fine. For example, remove find_package(PCL REQUIRED) and just use find_package(catkin REQUIRED COMPONENTS pcl_ros ...). You're also missing any PCL depends statements in package.xml, so add in a <depends>pcl_ros</depends>.

**Comment by Livox-SDK** [comment]
Thank you, zlacelle! 
We will have a test later!
