### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by 66695** [Livox-SDK/livox_ros_driver#141]
I compiled it in ubuntu20.04 with ros noetic, and with problem:
/home/xxx/ws_livox/src/livox_ros_driver/livox_ros_driver/lddc.cpp:343:31:   required from here
/opt/ros/noetic/include/ros/message_traits.h:125:14: error: ‘const class std::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >’ has no member named ‘__getMD5Sum’
  125 |     return m.__getMD5Sum().c_str();
      |            ~~^~~~~~~~~~~
......
/opt/ros/noetic/include/ros/message_traits.h:142:14: error: ‘const class std::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >’ has no member named ‘__getDataType’
  142 |     return m.__getDataType().c_str();
......
/home/xxx/ws_livox/src/livox_ros_driver/livox_ros_driver/lddc.cpp:343:31:   required from here
/opt/ros/noetic/include/ros/serialization.h:144:14: error: ‘const class std::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >’ has no member named ‘serializationLength’
  144 |     return t.serializationLength();
......
/home/xxx/ws_livox/src/livox_ros_driver/livox_ros_driver/lddc.cpp:343:31:   required from here
/opt/ros/noetic/include/ros/serialization.h:127:7: error: ‘const class std::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >’ has no member named ‘serialize’
  127 |     t.serialize(stream.getData(), 0);
      |     ~~^~~~~~~~~
____________________________________
where in the file:
https://github.com/Livox-SDK/livox_ros_driver/blob/880c46a91aaa602dbecf20e204da4751747b3826/livox_ros_driver/livox_ros_driver/lddc.cpp#L343
[](url) and 
https://github.com/Livox-SDK/livox_ros_driver/blob/880c46a91aaa602dbecf20e204da4751747b3826/livox_ros_driver/livox_ros_driver/lddc.cpp#L346
it seems that the Problem is **the transfom betwen**
pcl::shared_ptr<livox_ros::PointCloud> cloud 
**and**
sensor_msg::PointCloud2?
someone met the questiopn?

**Comment by 66695** [comment]
https://github.com/Livox-SDK/livox_ros_driver/pull/110 has mentioned.

**Comment by HernandoR** [comment]
any fix concluded?
