### ISSUE TITLE
Horizon使用livox_ros_driver点云存在拖影

### ISSUE THREAD

**Issue by ZhouZhuoL** [Livox-SDK/livox_ros_driver#15]
我们在livox_viewer下显示Horizon数据时正常，但使用livox_ros_driver时在rviz中观察到有1S以上的拖影，请问需要修改驱动中什么参数来解决这个问题

**Comment by PanZhichen** [comment]
set **Decay Time** of PointCloud2 msg to 0

**Comment by ZhouZhuoL** [comment]
> set **Decay Time** of PointCloud2 msg to 0

Thanks! It works,but we found if we set Decay Time to 0, the /livox/lidar pointcloud twinkling quickly.Is this a normal phenomenon?

**Comment by PanZhichen** [comment]
if the publish frequence of /livox/lidar  is 20Hz, set the Decay Time to 0.1
