### ISSUE TITLE
LIVOX AVIA 激光时间戳出错，imu发送逻辑问题(livox/lidar timestamp error and the publish logic of  imu is weird)

### ISSUE THREAD

**Issue by sychina** [Livox-SDK/livox_ros_driver#163]
When i tried to run `rosbag record` with livox avia and checked in `rqt_bag` , I found something weird.
1. lidar's timestamp is jumped each second.
![Screenshot from 2023-12-07 20-47-31](https://github.com/Livox-SDK/livox_ros_driver/assets/50667519/a9e87795-8906-4546-b0ca-cddd2002c754)
![Screenshot from 2023-12-07 20-47-41](https://github.com/Livox-SDK/livox_ros_driver/assets/50667519/1703fd45-6801-4d36-9623-690abbb12bf8)
![Screenshot from 2023-12-07 20-47-52](https://github.com/Livox-SDK/livox_ros_driver/assets/50667519/b818ea89-f33c-4a42-80d0-60c5f2e30728)
in seq.2188, the timestamp is 385.99943, but in seq.2189 and 2190, the timestamps are  386.9967 and 386.199. Where is 386.099 ????
2. What is the advantage of bundling 20 imu msgs to align lidar msgs, I still must to align them in the code because all the timestamps of the topics are in  a mess
![Screenshot from 2023-12-07 20-47-10](https://github.com/Livox-SDK/livox_ros_driver/assets/50667519/4da98109-e931-44b2-b0be-9fdcd6c37b17)
It looks like imu is 10Hz

**Comment by sychina** [comment]
![Screenshot from 2023-12-07 20-46-58](https://github.com/Livox-SDK/livox_ros_driver/assets/50667519/aacd5ff7-c1a4-441d-a8fb-841dc8ec04e0)
sorry this picture shoud be right. 

Thank you

**Comment by sychina** [comment]
Q1 miss one digital, Q1 sloved

**Comment by HP-Yin** [comment]
请问这个问题是怎么解决的呢？
How was this problem solved?

**Comment by sychina** [comment]
> 请问这个问题是怎么解决的呢？
> How was this problem solved?

没问题，仔细数了下时间戳的小数位数，其实没少。但是不太明白为何要把imu的数据挤到一起发过来

**Comment by HP-Yin** [comment]
我也看了一下，header.stamp是没问题的，他发送的时候写在了一个while循环里打包发送了
