### ISSUE TITLE
behavior when launching multiple sensors (without hub)

### ISSUE THREAD

**Issue by xmba15** [Livox-SDK/livox_ros_driver#22]
Hi, 
I tried to run the two horizon lidars with 
```bash
roslaunch livox_ros_driver livox_lidar_rviz.launch bd_list:="broadcast_lidar1&broadcast_lidar2"
```
I could see only one /livox/lidar pointcloud message? is it the correct behavior?
Should I expect to see two separate point cloud messages?

In the case of only one point cloud message, does that mean the ros package conducts the fusion of  point cloud internally?

I did not use livox hub for this experiment.
Thanks for the support.

**Comment by Livox-SDK** [comment]
（1）replace broadcast_lidar1 or broadcast_lidar1  with your lidar broadcast code（15 char） ，
         for example， your lidar broadcast code is “0TFDG3B006H2Z11“，the command should be：
        roslaunch livox_ros_driver livox_lidar_rviz.launch bd_list:="0TFDG3B006H2Z11”

**Comment by Livox-SDK** [comment]
（2）You can use：
 roslaunch livox_ros_driver livox_lidar_rviz.launch
The ros driver will connect LiDAR uint(s) automatically
