### ISSUE TITLE
Horizon: Recording to rosbag including internal IMU data

### ISSUE THREAD

**Issue by dmirk** [Livox-SDK/livox_ros_driver#26]
Hi, i try to record to rosbag using the 
livox_lidar_msg.launch file.
So I changed the arg "rosbag_enable" to true, which records succesfully to a file located in ~/.ros
When I want to play that file with the Livox-SDK/livox_horizon_loam package it works successfully only with the default launch file.

If I use the "_imu" version (changed line 24 in the launch file to use the internal IMU of horizon) nothing happens when playing the rosbag.

Is this an issue with the recorded bag, or with the loam package?

**Comment by PanZhichen** [comment]
hi~ you can use `$ rosbag info YOUR_RECORDED_BAG.bag` to check if there is a topic named _/livox/imu_ in your rosbag. If not, please modify the json config file as mentioned [here](https://github.com/Livox-SDK/livox_ros_driver#5-configure-lidar-parameters) to enable the imu output.
In addition, the README for Livox-SDK/livox_horizon_loam has been updated, hope it helps you.
