### ISSUE TITLE
How to create a depth image ?

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [Livox-SDK/livox_ros_driver#27]
The majority of object segmentation methods utilise a depth image in their learning and inference.
Is there a way to specify the dimensions of the depth image from livox horizon pointcloud data?
Is there a method to create depth images in the SDK?

**Comment by Livox-SDK** [comment]
Sorry, Tariq-Abuhashim , our SDK don't support it

**Comment by xmba15** [comment]
@Tariq-Abuhashim I actually created a library here that supports spherical projection of livox point cloud data into 2d image here.
https://github.com/xmba15/livox_lidar_data_manipulation

**Comment by xmba15** [comment]
![spherical_projection](https://user-images.githubusercontent.com/18694765/89715932-3731c180-d9e4-11ea-9d07-b64ebc1e1ca0.gif)
here is the result sample
