### ISSUE TITLE
Which kind of coordinates does the Livox follow and how to calibrate the imu mounted on the Livox sensor?

### ISSUE THREAD

**Issue by SandW** [Livox-SDK/livox_ros_driver#3]
I want to align the Livox ROS coordinates with the IMU coordinates. Does anyone know how to calibrate and find some visual explanations? Thanks in advance!

**Comment by TobiMiller** [comment]
right hand side. x points out of the sensor and z points up

**Comment by SandW** [comment]
Thank you!

**Comment by SandW** [comment]
Are there any calibration tools?

**Comment by Livox-SDK** [comment]
Hi, SandW
     I'm very Sorry, it is not currently supported.

**Comment by SandW** [comment]
OK, thanks!
