### ISSUE TITLE
可以同时启动两个驱动程序读取一个livox激光雷达的数据吗？

### ISSUE THREAD

**Issue by xielinjiang** [Livox-SDK/livox_ros_driver#30]
你好：
  我可以同时启动两个驱动程序读取一个livox激光雷达的数据吗？
谢谢！

**Comment by Livox-SDK** [comment]
不可以，LiDAR 不支持多播

**Comment by xielinjiang** [comment]
好的，谢谢

**Comment by russellyq** [comment]
你好，那请问怎么同时launch多个lidar呢？只能用livox hub吗？

谢谢

**Comment by russellyq** [comment]
@Livox-SDK

**Comment by goodstudy666-na** [comment]
@xielinjiang 同时启动两个驱动程序读取一个livox激光雷达的数据，请问您有解决办法了吗？

**Comment by goodstudy666-na** [comment]
@russellyq 同时启动两个驱动程序读取一个livox激光雷达的数据，请问您有解决办法了吗？
