### ISSUE TITLE
Livox-hardware on WSL2 Ubuntsu

### ISSUE THREAD

**Issue by dotchang** [Livox-SDK/livox_ros_driver#40]
WSL2 is very useful application for testing linux applications.
I tried to use Livox-mapping on Ubuntsu18.04 and WSL2.
The rosbag example worked well.

But the example with horizon-hardware does not work.
The application could not find the device.
Are there good way to run the horizon hardware on WSL2 system of windows10?

**Comment by Livox-SDK** [comment]
Hi, dotchang,
     Does Your WSL2 have separate ip address?
     Or you can check the windows firewall.
