### ISSUE TITLE
Client [/rviz] wants topic /livox/lidar to have datatype/md5sum

### ISSUE THREAD

**Issue by echoGee** [Livox-SDK/livox_ros_driver#41]
Running a livox_lidar_msg.launch in one PC, I get the following error 

> Set coordinate success!
> [2020-07-02 20:07:13.516] [console] [info]  Recieve Ack: Set 1 Id 6 Seq 7  [command_handler.cpp] [OnCommand] [129]
> Set return mode success!
> [2020-07-02 20:07:13.516] [console] [info]  Recieve Ack: Set 1 Id 8 Seq 8  [command_handler.cpp] [OnCommand] [129]
> Set imu rate success!
> [2020-07-02 20:07:13.517] [console] [info]  Send Command: Set 0 Id 4 Seq 9  [command_channel.cpp] [Send] [241]
> Lidar00[1HDDGC500100821] queue size : 4000 4096
> Lidar00[1HDDGC500100821] imu queue size : 256 256
> [ INFO] [1593734833.539689247]: Support only one topic.
> [2020-07-02 20:07:13.540] [console] [info]  Recieve Ack: Set 0 Id 4 Seq 9  [command_handler.cpp] [OnCommand] [129]
> Lidar start sample success
> [ INFO] [1593734833.544097289]: livox/imu publish imu data, set ROS publisher queue size 128
> [ INFO] [1593734833.645416044]: Support only one topic.
> [ INFO] [1593734833.647921107]: livox/lidar publish use livox custom format, set ROS publisher queue size 256
> [ERROR] [1593734849.259791528]: Client [/rviz] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
> [ERROR] [1593734891.463433635]: Client [/rviz] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
> [ERROR] [1593735250.868341960]: Client [/rviz] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
> [ERROR] [1593735384.721011751]: Client [/rviz] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
> 

![image](https://user-images.githubusercontent.com/518314/86419585-9859cd00-bca1-11ea-82a4-4731523257f2.png)

when open the same(same commit) rviz config file in a different PC. 
Any suggestions ?

**Comment by Livox-SDK** [comment]
Hi echoGee,
    The /livox/CustomMsg is not supportted by rviz!
    Modify the arg "xfer_format" to  "0" in launch file if you want to display pointcloud by rviz please!
