### ISSUE TITLE
set high sensitivity fail and topic is empty

### ISSUE THREAD

**Issue by zhangmaoxiansheng** [Livox-SDK/livox_ros_driver#47]
The /lidar/livox topic is empty and rviz shows nothing. The terminal print ""enable_high_sensitivity": false", however, I have set "enable_high_sensitivity": false in the configure json. The lidar is tele 15.
Terminal info:
[2020-07-26 16:43:45.342] [console] [info]  Recieve Ack: Set 0 Id 11 Seq 17  [command_handler.cpp] [OnCommand] [129]
Set high sensitivity fail, try again!

**Comment by Livox-SDK** [comment]
Hi,zhangmaoxiansheng:
   Can you check the firmware version and Livox-SDK version？

**Comment by zhangmaoxiansheng** [comment]
Thx! I solved the problem by updating the firmware to the latest version.
