### ISSUE TITLE
Horizon Imu message orientation all 0.0 values

### ISSUE THREAD

**Issue by AndyBell54** [Livox-SDK/livox_ros_driver#52]
I'm trying to get the imu orientation values from the ROS /livox/imu topic, and when looking at the message values, all quaternion values are 0.0. The configuration json file has set "imu_rate": 1. Not sure where to go next?

**Comment by Livox-SDK** [comment]
Hi,  AndyBell54 
    There are only six-axis raw data of angular velocity and gravitational acceleration in the imu message.
