### ISSUE TITLE
Ros2 driver

### ISSUE THREAD

**Issue by amakurin** [Livox-SDK/livox_ros_driver#53]
Hi! Do you have ros2 driver \ plans to implement it?

**Comment by Livox-SDK** [comment]
Hi,amakurin
The development of the ros2 driver is already in the agenda, and the official release time may be two months later.
thanks!

**Comment by amakurin** [comment]
Thank you for info! If it is possible we will be glad to test beta or RC. Thank you again.

**Comment by Livox-SDK** [comment]
Hi,amakurin
livox_ros2_driver is released, you can test it, thandks!
https://github.com/Livox-SDK/livox_ros2_driver

**Comment by amakurin** [comment]
OMG Thank you so much! Will check it out!

**Comment by jinzhongxiao** [comment]
Avia Lidar support by ROS2? I  didn't found any avia lidar ros2 driver
