### ISSUE TITLE
How to get the Lidar caliberation parameters into ROS

### ISSUE THREAD

**Issue by nithi89** [Livox-SDK/livox_ros_driver#6]
The original Livox visualization software has a feature to do extrinsic calibration of the lidar, which can be stored to the Lidar itself.

When I try to receive the lidar information in ROS, the calibration doesn't seem to take effect and each time, the orientation of each lidar changes arbitrarily.

How can I get calibrated Lidar data from the Livox via ROS?

**Comment by Livox-SDK** [comment]
The new version（v2.0.0） of livox_ros_driver support the extrinsic, it will be released in next two week!

**Comment by nithi89** [comment]
Is it possible to get it earlier, we have a deadline to meet in the coming week!

**Comment by Livox-SDK** [comment]
hi,nithi89
  The new version of livox_ros_driver is released , you can update it now.

**Comment by nithi89** [comment]
Thank you guys!
