### ISSUE TITLE
What is the unit of acceleration in the internal IMU of the horizon?

### ISSUE THREAD

**Issue by kamibukuro5656** [Livox-SDK/livox_ros_driver#63]
Hello

What are the units of the internal IMU in Horizon?
The output value is too small for m/s^2.
It's probably scaled to 10 or something close to that, is that correct?

**Comment by Livox-SDK** [comment]
Sorry，the unit is g.

**Comment by kamibukuro5656** [comment]
Thank you.
I understand.
