### ISSUE TITLE
What's the difference between xfer_format and output_type in the launch file?

### ISSUE THREAD

**Issue by h-k8888** [Livox-SDK/livox_ros_driver#65]
I'm confused.
What's the difference between **xfer_format** and **output_type** in the launch file?

**Comment by Livox-SDK** [comment]
xfer_format defines the message format used by livox_ros_driver when publishing livox pointcloud, there are there format you can select；
Use output_type to choose whether to output the point cloud point data to the rosbag file or the ros communication node;
