### ISSUE TITLE
PointCloud format

### ISSUE THREAD

**Issue by YangSiri** [Livox-SDK/livox_ros_driver#67]
Hi, @Livox-SDK  

I'm curious about the PointXYZRTL format of livox lidar point cloud. Are all livox series support this? What does the _tag_ and _line_ parameter mean? Because I found these two value are 0 for MID-40 data. And what about the Customized point cloud format?

Looking forward to your help ;>

**Comment by Livox-SDK** [comment]
Hi,YangSiri
MID-40/MID-100 doesn't support the tag flag, but Horizon/Tele/Mid70/Mid70Pro support it.
The Customized point cloud format is livox defined format , the description of this pointcloud format is in README.md

**Comment by YangSiri** [comment]
Thanks, @Livox-SDK 

Could you please show me where i can find the understanding of _tag_ and _line_ flag? And do all livox lidars support Customized point cloud format?

**Comment by Livox-SDK** [comment]
Hi,YangSiri
    you can reference the following link:
[Livox-SDK-Communication-Protocol](https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol)

**Comment by goldqiu** [comment]
Is there only one lasers in Mid70？   I also printf the information of the ‘line’ ,but it has no output information. Could you please answer my question? Thank you.
