### ISSUE TITLE
GPS时间同步问题

### ISSUE THREAD

**Issue by ShiJian1995** [Livox-SDK/livox_ros_driver#72]
我们自己的PPS脉冲的高电平时间999ms，低电平时间1ms，电压为3.3V，无法进行时间同步；查看文档说对PPS信号有要求，我们又用信号发生器模拟了这样的PPS信号，但是仍然不能触发，请问是怎么回事？我们的操作步骤：1、更改config配置文件，false->true，串口ttyUSB0和波特率9600，对应数字2；2、串口发布GPRMC数据格式；3、时间同步线：黑线接地，蓝线接PPS；上述操作后，抓取的bag文件中的time stamp 仍然是ros的时间不是GPS时间，同时在终端输出信息中 同步状态位仍然为0。
附：文档中说PPS信号是上升沿触发，然而又对PPS信号的高电平时间有限制，这是为什么？

**Comment by Livox-SDK** [comment]
单独的pps触发，无法将时间信息同步到 LiDAR 中；时间戳同步相关的内容，请参考下面链接：
[time-synchronization](https://github.com/Livox-SDK/Livox-SDK/wiki/livox-device-time-synchronization-manual)

**Comment by YangSiri** [comment]
Hi, @Livox-SDK 

请问AVIA是使用Livox Converter 1.0吗？
