### ISSUE TITLE
PPS 同步的时间戳问题

### ISSUE THREAD

**Issue by Stevenhyh1** [Livox-SDK/livox_ros_driver#85]
在使用PPS同步时，按照documentation点云的时间应该是从归零后重新开始计算，也就是小于一秒。但实际发布的点云时间是ros time now，导致我没有办法按照教程中的伪代码写同步程序。请问这个问题怎么解决？

**Comment by Livox-SDK** [comment]
pps 同步模式下，ros driver 在点云的原始时间戳基础上补偿了接收时间；将 lds.cpp 中部分代码注释掉，可以得到你想要的结果：
![image](https://user-images.githubusercontent.com/45850995/117001935-86a7e280-ad15-11eb-9847-56f27a744c37.png)
