### ISSUE TITLE
What is imu_rate?

### ISSUE THREAD

**Issue by finostro-amtc** [Livox-SDK/livox_ros_driver#9]
Hello, 
I am just testing mid-40 sensor and i see the imu_rate parameter in the config file?
What does this do? Is there an imu inside the sensor?

Thanks

**Comment by Livox-SDK** [comment]
For mid-40 sensor, you should ignore the imu_rate parameter.
There is a imu sensor in Horizon(our new generation LiDAR), but the imu
rate is fixed to 200Hz now, this parameter will be deprecated!

**Comment by finostro** [comment]
ok
thank you!
