### ISSUE TITLE
Question about frequency and resolution

### ISSUE THREAD

**Issue by JasperTan97** [Livox-SDK/livox_ros_driver#92]
Hi! I am using a livox horizon lidar and I have changed by framerate from 10Hz to 50Hz. Does this mean that my file size will get 5 times bigger and all frames retain the same resolution, or has the resolution of each frame decreased by 5 times?

Thank you

**Comment by Livox-SDK** [comment]
Hi JasperTan97,

Change the framerate from 10Hz to 50Hz wont't change the size of the point cloud received; 
framerate from 10Hz to 50Hz will only change how many bag displayed at one time

**Comment by zenkichen** [comment]
How can I change the framerate is ROS driver. not the publish frequency.
