### ISSUE TITLE
Where is the bag path?

### ISSUE THREAD

**Issue by ManChrys** [Livox-SDK/livox_ros_driver#94]
Lidar : Livox mid 40
OS : Ubuntu 18.04

Hello guys,

i have a question. When i use livox_lidar.launch file i enable the "rosbag_enable" option. 

~~~
<node pkg="rosbag" type="record" name="record" output="screen"
          		args="-a"/>
~~~

In the end of the file i saw the line above, so if i recard all topics, because we use -a option, where is the bag file saved? I cant find the path. Should i set the path inside the launch file? and if yes how ?

Thanks in advance.

**Comment by Livox-SDK** [comment]
Hi,ManChrys
    you can append the path to "-a", this parameter item is not ofen used.

**Comment by Livox-SDK** [comment]
you can use the "rosbag record" command in separate terminal

**Comment by ManChrys** [comment]
yy that's actually what I did!!

Thank you guys.
