### ISSUE TITLE
Problem with false pointcloud point

### ISSUE THREAD

**Issue by nilic993** [Livox-SDK/livox_ros_driver#96]
Hi,
I've mounted a Mid-70 unit on my robot so that I can use the point cloud it generates to create a costmap for navigation. It works mostly fine but as you can see in the images below there's a single point that shows up exactly where the lidar itself is (see where the green arrow is pointing). It appears even when the lidar is completely covered up with cloth (second image). I can't get rid of that single point and it's causing me trouble because it shows up in the costmap, and it looks like it's "inside" the lidar.

![p1](https://user-images.githubusercontent.com/55019479/127625512-9862298a-e22e-4743-8e2a-83f3efee65e5.png)

![p2](https://user-images.githubusercontent.com/55019479/127625525-5bdd22ee-8f8b-41d1-8f46-8fb337cf8778.png)

Edit: I've noticed that the point is in the center of the livox_frame reference frame:

![6](https://user-images.githubusercontent.com/55019479/127652399-37353202-de96-4378-ac8d-335c8891cd5f.png)

**Comment by Livox-SDK** [comment]
H, nilic993

These points are there since these point is "not received"
You can simply remove these points by secondary development
