### ISSUE TITLE
How to merge multi Lidars PointCloud with hub?

### ISSUE THREAD

**Issue by h-wata** [Livox-SDK/livox_ros_driver#97]
Hi,
I try to connect 5 Horizon to Livox Hub and save lvx file.
After that lvx file convert to bag file by `lvx_to_rosbag.launch`.

**Configuration**
- timesync: ptp
- lvx_to_rosbag.launch default configuration
    -  publish_freq = 10

**livox viewer(lvx)**
![livox-viewer](https://user-images.githubusercontent.com/20681658/128333125-780e74ca-7587-444d-835c-496df944b3de.gif)
 
I confused that `/livox/lidar` topic in .bag file seems to each lidar pointcloud as follow,
**RVIZ**
![livox-rviz](https://user-images.githubusercontent.com/20681658/128333115-86b2410a-ddb2-472d-b3fc-f62bfb09b218.gif)

```
rostopic hz /livox/lidar
subscribed to [/livox/lidar]
average rate: 54.471
        min: 0.000s max: 0.100s std dev: 0.03807s window: 50
average rate: 52.139
        min: 0.000s max: 0.100s std dev: 0.03877s window: 100
average rate: 51.392
        min: 0.000s max: 0.100s std dev: 0.03871s window: 150
```

Let me know how to publish 5 Lidars points at once like .lvx file.

**Comment by Livox-SDK** [comment]
Set Decay Time to 0.1, 0.2, 0.5, or 1, etc. 
The "Decay Time" must be  greater than 0.

**Comment by h-wata** [comment]
> Set Decay Time to 0.1, 0.2, 0.5, or 1, etc.
> The "Decay Time" must be greater than 0.

What you mean is that one topic is published from only one lidar, right?
If so, I use the node to merge PointCloud2 topic like [points_concat_filter](https://github.com/Autoware-AI/core_perception/blob/master/points_preprocessor/launch/points_concat_filter.launch).

Thank you for reply.

**Comment by Livox-SDK** [comment]
"What you mean is that one topic is published from only one lidar, right?"
yes，you can sync and merge all lidars when you receive enough topics!

**Comment by h-wata** [comment]
Thanks for your support!
